/**
 * Config plugin: the iOS home screen widget, a WidgetKit extension.
 *
 * iOS gets a small "now playing" widget: the track the app last wrote, its
 * cover, a progress bar and two links (the album, play/pause). It is a second
 * binary inside the app bundle, so it needs three things prebuild cannot know
 * about on its own:
 *
 * - the sources, which live in `ios-widget/ResonusWidget/` because `ios/` is
 *   generated and `.gitignore`d: they are copied in on every prebuild;
 * - a target to build them, with the Info.plist and the entitlements that go
 *   with it, and a copy-files phase so the app embeds the result;
 * - the App Group both halves read `nowPlaying` and the cover from. Without
 *   it on the app, the widget's container is never created and it would sit
 *   there empty.
 *
 * The bundle id is the app's with the target's name on the end, which is what
 * Xcode expects of an extension: `com.juananzzz.resonus.ResonusWidget`.
 *
 * ios/ is in .gitignore and regenerated by prebuild, so this has to be a
 * plugin: hand edits would be lost.
 */
const fs = require('fs');
const path = require('path');

const {
  withAppDelegate,
  withDangerousMod,
  withEntitlementsPlist,
  withXcodeProject,
} = require('@expo/config-plugins');

/** Shared with the widget's own `ResonusWidget.entitlements`. */
const APP_GROUP = 'group.com.juananzzz.resonus';

/**
 * The refresh task whose only job is to get the app running: the widget's
 * play button schedules it, and the system launches the app in the
 * background to run it. Spelled the same in `PlaybackToggleIntent` and in
 * the register call injected into the AppDelegate below; both plists
 * (app.json for the app, `ResonusWidget-Info.plist` for the extension)
 * permit it.
 */
const PRESS_TASK = 'com.juananzzz.resonus.pendingPressRefresh';

const NAME = 'ResonusWidget';
const BUNDLE_ID = 'com.juananzzz.resonus.ResonusWidget';

/** The widget's sources, by name; they live at `<root>/ios-widget/ResonusWidget`. */
const FILES = [
  'ResonusWidget.swift',
  'WidgetData.swift',
  // The runtime's own reading of the app group, compiled into both targets.
  'SharedAppGroup.swift',
  // The play button's press: an intent, so it toggles without opening the
  // app. It reads the group above, hence it goes where the group's reader
  // goes.
  'PlaybackToggleIntent.swift',
  'widget-icon.png',
  'ResonusWidget-Info.plist',
  'ResonusWidget.entitlements',
];

/** What `xcode` cannot work out for itself, given only the file name. */
const FILE_TYPES = {
  'widget-icon.png': 'image.png',
  'ResonusWidget.entitlements': 'text.plist.entitlements',
};

module.exports = function withResonusWidget(config) {
  config = withEntitlementsPlist(config, (cfg) => {
    const groups = cfg.modResults['com.apple.security.application-groups'] ?? [];
    if (!groups.includes(APP_GROUP)) groups.push(APP_GROUP);
    cfg.modResults['com.apple.security.application-groups'] = groups;
    return cfg;
  });

  config = withDangerousMod(config, [
    'ios',
    (cfg) => {
      const root = cfg.modRequest.projectRoot;
      const into = path.join(root, 'ios', NAME);
      const source = path.join(root, 'ios-widget', NAME);
      fs.mkdirSync(into, { recursive: true });
      for (const file of FILES) {
        fs.copyFileSync(path.join(source, file), path.join(into, file));
      }
      return cfg;
    },
  ]);

  // The register call for the press's background launch, put where iOS looks
  // for it: before `didFinishLaunchingWithOptions` returns. The handler does
  // not touch the group — the press waits there, JavaScript takes it on
  // startup (the cold case) or on its one-second poll (the suspended one) —
  // it only keeps the process up long enough for that to happen.
  config = withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') return cfg;
    const before = cfg.modResults.contents;
    if (before.includes(PRESS_TASK)) return cfg;
    const marker =
      'return super.application(application, didFinishLaunchingWithOptions: launchOptions)';
    cfg.modResults.contents = before
      .replace(
        'import ReactAppDependencyProvider',
        'import ReactAppDependencyProvider\nimport BackgroundTasks',
      )
      .replace(
        marker,
        `BGTaskScheduler.shared.register(forTaskWithIdentifier: "${PRESS_TASK}", using: nil) { task in
      DispatchQueue.main.asyncAfter(deadline: .now() + 20) {
        task.setTaskCompleted(success: true)
      }
    }

    ${marker}`,
      );
    if (
      !cfg.modResults.contents.includes(PRESS_TASK) ||
      !cfg.modResults.contents.includes('import BackgroundTasks')
    ) {
      throw new Error('withResonusWidget: AppDelegate template not as expected');
    }
    return cfg;
  });

  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    if (project.pbxTargetByName(NAME)) return cfg;

    const objects = project.hash.project.objects;
    // `xcode` writes a target dependency only when these sections already
    // exist, and a fresh Expo project has neither. Without the dependency
    // Xcode builds the app first and finds no .appex to embed.
    objects.PBXContainerItemProxy = objects.PBXContainerItemProxy || {};
    objects.PBXTargetDependency = objects.PBXTargetDependency || {};

    const target = project.addTarget(NAME, 'app_extension', NAME, BUNDLE_ID);
    const sources = project.addBuildPhase([], 'PBXSourcesBuildPhase', 'Sources', target.uuid);
    const resources = project.addBuildPhase([], 'PBXResourcesBuildPhase', 'Resources', target.uuid);

    const group = project.addPbxGroup(FILES, NAME, NAME);
    // Not attached to anything by itself: it hangs off the project's root.
    const root = project.pbxProjectSection()[project.hash.project.rootObject];
    objects.PBXGroup[root.mainGroup].children.push({ value: group.uuid, comment: NAME });

    // `addPbxGroup` also files a build file per entry; the sources and the
    // icon are the two halves of the widget that actually get compiled and
    // bundled. The plist and the entitlements are named by build settings, so
    // their build files are dropped rather than left dangling.
    const buildFiles = project.pbxBuildFileSection();
    const phases = [
      ['.swift', sources, 'Sources'],
      ['.png', resources, 'Resources'],
    ];
    for (const child of group.pbxGroup.children) {
      const key = Object.keys(buildFiles).find(
        (entry) => !entry.endsWith('_comment') && buildFiles[entry].fileRef === child.value,
      );
      if (!key) continue;
      // `xcode` has no idea what a png or an entitlements file is, and a file
      // of type `unknown` is one Xcode has to guess at.
      const type = FILE_TYPES[child.comment];
      if (type) project.pbxFileReferenceSection()[child.value].lastKnownFileType = type;
      const phase = phases.find(([suffix]) => child.comment.endsWith(suffix));
      if (!phase) {
        delete buildFiles[key];
        delete buildFiles[`${key}_comment`];
        continue;
      }
      phase[1].buildPhase.files.push({ value: key, comment: `${child.comment} in ${phase[2]}` });
    }

    const list = objects.XCConfigurationList[target.pbxNativeTarget.buildConfigurationList];
    for (const entry of list.buildConfigurations) {
      const settings = objects.XCBuildConfiguration[entry.value].buildSettings;
      // `path.join` puts Windows separators in here, and a pbxproj is only
      // ever read on macOS. The rest is what Xcode writes for an extension
      // that ships with its own Info.plist.
      settings.INFOPLIST_FILE = `"${NAME}/${NAME}-Info.plist"`;
      settings.CODE_SIGN_ENTITLEMENTS = `"${NAME}/${NAME}.entitlements"`;
      settings.IPHONEOS_DEPLOYMENT_TARGET = '16.4';
      settings.SWIFT_VERSION = '5.0';
      settings.TARGETED_DEVICE_FAMILY = '"1,2"';
      settings.CURRENT_PROJECT_VERSION = '1';
      // Xcode wants an extension to carry the app's own version: it warns on
      // the mismatch, and the warning is worth not having.
      settings.MARKETING_VERSION = String(config.version ?? '1.0');
      settings.CLANG_ENABLE_MODULES = 'YES';
    }

    // `xcode` writes every field a file left unset as `key = undefined;`,
    // which is not a plist value: `explicitFileType = undefined` would tell
    // Xcode the Swift sources have no type at all.
    stripUndefined(objects);

    return cfg;
  });
};

/** Drops the fields the parser left as `undefined` before they are written. */
function stripUndefined(value) {
  if (Array.isArray(value)) {
    value.forEach(stripUndefined);
    return;
  }
  if (!value || typeof value !== 'object') return;
  for (const key of Object.keys(value)) {
    if (value[key] === undefined) delete value[key];
    else stripUndefined(value[key]);
  }
}
