/**
 * Config plugin: opts the app out of Android's "Bold text" weight adjustment.
 *
 * Android applies that setting when text is DRAWN, but React Native measures
 * text without it, so every string is laid out narrower than it ends up being
 * and the last letter falls off the end (issue #60: "MP3" reads "MP", "OPUS"
 * reads "OPU", "2.6 GB" reads "2.6"). It is an old React Native bug with no fix
 * upstream, and on Android `AccessibilityInfo.isBoldTextEnabled()` is hardcoded
 * to false, so nothing in JS can even detect the setting to work around it.
 *
 * What is left is to decline the adjustment: text is then measured and drawn at
 * the same weight and nothing is cut. The cost is that the app renders at its
 * normal weight for someone who turned the setting on.
 *
 * android/ is in .gitignore and regenerated by prebuild, so this has to be a
 * plugin: editing MainActivity by hand would be lost.
 */
const { withMainActivity } = require('@expo/config-plugins');

/** Enough to recognise our own work on a second run. */
const MARKER = 'fontWeightAdjustment';

const IMPORTS = `import android.content.Context
import android.content.res.Configuration
import android.os.Build`;

const OVERRIDE = `
  /**
   * Declines Android's "Bold text" weight adjustment. React Native measures
   * text without it and draws it with it, so the last letter of a string gets
   * cut off (issue #60). See plugins/withoutFontWeightAdjustment.js.
   */
  override fun attachBaseContext(newBase: Context) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S) {
      super.attachBaseContext(newBase)
      return
    }
    val config = Configuration(newBase.resources.configuration)
    config.fontWeightAdjustment = 0
    super.attachBaseContext(newBase.createConfigurationContext(config))
  }
`;

function applyOverride(source) {
  if (source.includes(MARKER)) return source; // already applied
  if (!source.includes('import android.os.Build')) {
    throw new Error('withoutFontWeightAdjustment: MainActivity has no Build import to anchor on');
  }
  // Last in the class, rather than wedged between one of the generated methods
  // and the comment that explains it.
  const withImports = source.replace('import android.os.Build', IMPORTS);
  const end = withImports.lastIndexOf('}');
  if (end === -1) {
    throw new Error('withoutFontWeightAdjustment: MainActivity has no closing brace');
  }
  return withImports.slice(0, end) + OVERRIDE + withImports.slice(end);
}

module.exports = function withoutFontWeightAdjustment(config) {
  return withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error('withoutFontWeightAdjustment only supports a Kotlin MainActivity');
    }
    cfg.modResults.contents = applyOverride(cfg.modResults.contents);
    return cfg;
  });
};
