#!/usr/bin/env node
/**
 * Writes `docs/TRANSLATION-CONTEXT.md`: every string in the app, under the
 * screen it shows up on, with what it means where that needed saying.
 *
 *   pnpm i18n:docs            write it
 *   pnpm i18n:docs --check    fail if it is out of date (this is what CI runs)
 *
 * The tools hand this context to anybody who has cloned the repo and can run
 * pnpm. Plenty of translation happens without either: somebody opens `ru.json`
 * in the GitHub editor, or reads the file on their phone to decide whether to
 * take it on. This is that same context as one page they can browse, and it is
 * generated on purpose. The table it replaces was written by hand and had spent
 * three releases describing keys that no longer existed, which is the failure
 * this whole thing exists to stop: a second copy of the truth always rots. CI
 * regenerates it and fails if it moved, so it cannot.
 *
 * Grouped by screen rather than alphabetically, because that is how a
 * translation is actually checked: you look at one screen, in the app or in
 * your head, and read down its words to see whether they sit together.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import { ROOT, callSites, enKeys, keepEnglish, meaning, whereShown } from './i18n-lib.mjs';

const OUT = join(ROOT, 'docs/TRANSLATION-CONTEXT.md');
const check = process.argv.includes('--check');

const sites = callSites();
const todoKeys = enKeys.filter((k) => !keepEnglish.has(k));

// A string is filed under the screens it shows on. One used in more than three
// places is not about a screen any more, it is a word the whole app uses, and
// listing it under nine headings would only make each of them longer.
const EVERYWHERE = 'Used all over the app';
const byScreen = new Map();
const file = (screen, key) => {
  if (!byScreen.has(screen)) byScreen.set(screen, []);
  byScreen.get(screen).push(key);
};

for (const key of todoKeys) {
  const where = whereShown(key, sites);
  if (!where || (where.includes(' and ') && where.includes(' more'))) file(EVERYWHERE, key);
  else {
    // The screens, not the file the string is written in: "Radio", not
    // "RadioEditSheet". `whereShown` has already worked that out.
    for (const screen of where.split(' · in ')[0].split(', ')) file(screen, key);
  }
}

const escape = (s) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const lines = [
  '# Where every string shows up',
  '',
  '<!-- Generated by `pnpm i18n:docs`. Do not edit by hand: a second copy of',
  '     this written by hand is what used to rot. Notes live in',
  '     `src/i18n/context.jsonc`, and where a string shows up is read off the',
  '     code, so both are fixed at the source and this page follows. -->',
  '',
  `Every string the app can show, under the screen it shows up on. ${todoKeys.length} of them.`,
  'The second column is only filled in where the English is ambiguous on its own',
  'If one tripped you up and the column is empty, that is worth telling us, and',
  'the answer goes into `src/i18n/context.jsonc` where the next translator of the',
  'next language gets it too.',
  '',
  'See [TRANSLATING.md](../TRANSLATING.md) for how to translate. If you have the',
  'repo cloned, `pnpm i18n:scaffold <locale>` puts all of this next to the strings',
  'you are actually typing into, which is easier than reading it here.',
  '',
];

const screens = [...byScreen.keys()]
  .filter((s) => s !== EVERYWHERE)
  .sort((a, b) => a.localeCompare(b));

for (const screen of [...screens, ...(byScreen.has(EVERYWHERE) ? [EVERYWHERE] : [])]) {
  const keys = [...new Set(byScreen.get(screen))].sort((a, b) => a.localeCompare(b));
  lines.push(`## ${screen}`, '', '| String | What it is |', '| --- | --- |');
  for (const key of keys) {
    lines.push(`| \`${escape(key)}\` | ${escape(meaning(key))} |`);
  }
  lines.push('');
}

if (keepEnglish.size) {
  lines.push(
    '## Left in English on purpose',
    '',
    'These are the Diagnostics measurements. They end up in a GitHub issue, often',
    'as a screenshot, and whoever reads them there does not speak every language we',
    'ship. `pnpm i18n:status` does not count them as missing.',
    '',
  );
  for (const key of keepEnglish) lines.push(`- \`${escape(key)}\``);
  lines.push('');
}

const out = lines.join('\n');

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== out) {
    console.error('docs/TRANSLATION-CONTEXT.md is out of date. Run: pnpm i18n:docs');
    process.exit(1);
  }
  console.log('docs/TRANSLATION-CONTEXT.md is up to date ✓');
  process.exit(0);
}

mkdirSync(join(ROOT, 'docs'), { recursive: true });
writeFileSync(OUT, out);
console.log(`docs/TRANSLATION-CONTEXT.md: ${todoKeys.length} strings under ${screens.length} screens`);
