#!/usr/bin/env node
/**
 * Builds the icon font the app draws with, from `src/components/icon-map.json`.
 *
 *   pnpm icons
 *
 * The map says which Phosphor icon, regular (`r`) or filled (`f`), stands in
 * for each Ionicons name the code uses. This fetches the Phosphor release
 * pinned below, writes the codepoints of those icons to
 * `src/components/iconGlyphs.ts` and cuts the two fonts down to just them
 * under `assets/fonts/`: the whole set is 940 KB, the icons we use are 30.
 *
 * Adding an icon is a line in the map and a run of this. Needs `npm` and
 * fonttools' `pyftsubset` on the PATH.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const PHOSPHOR = '@phosphor-icons/web@2.1.2';

const map = JSON.parse(readFileSync(join(ROOT, 'src/components/icon-map.json'), 'utf8'));

const tmp = mkdtempSync(join(tmpdir(), 'phosphor-'));
try {
  execFileSync('npm', ['pack', PHOSPHOR, '--silent'], { cwd: tmp });
  execFileSync('sh', ['-c', 'tar xzf *.tgz'], { cwd: tmp });
  const src = join(tmp, 'package/src');

  /** Name → codepoint, from the stylesheet each weight ships with. */
  const codepoints = (weight) => {
    const css = readFileSync(join(src, weight, 'style.css'), 'utf8');
    const out = {};
    for (const m of css.matchAll(/\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)"/g)) {
      out[m[1]] = parseInt(m[2], 16);
    }
    return out;
  };
  const all = { r: codepoints('regular'), f: codepoints('fill') };

  const used = { r: {}, f: {} };
  for (const [ion, [name, weight]] of Object.entries(map)) {
    const cp = all[weight]?.[name];
    if (cp === undefined) throw new Error(`${ion}: Phosphor has no "${name}" in weight "${weight}"`);
    used[weight][name] = cp;
  }

  const subset = (weight, from, to) => {
    const unicodes = Object.values(used[weight]).map((cp) => `U+${cp.toString(16)}`).join(',');
    execFileSync('pyftsubset', [join(src, from), `--unicodes=${unicodes}`, `--output-file=${join(ROOT, to)}`]);
  };
  subset('r', 'regular/Phosphor.ttf', 'assets/fonts/Phosphor.ttf');
  subset('f', 'fill/Phosphor-Fill.ttf', 'assets/fonts/Phosphor-Fill.ttf');

  const sorted = (o) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));
  writeFileSync(
    join(ROOT, 'src/components/iconGlyphs.ts'),
    `// Generated by \`pnpm icons\` from icon-map.json. Do not edit.\n` +
      `export const REGULAR: Record<string, number> = ${JSON.stringify(sorted(used.r), null, 2)};\n\n` +
      `export const FILL: Record<string, number> = ${JSON.stringify(sorted(used.f), null, 2)};\n`,
  );
  console.log(`${Object.keys(map).length} icons, ${Object.keys(used.r).length} regular and ${Object.keys(used.f).length} filled glyphs.`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
